dirs:
  raw_dir: &raw_dir "${RAW_DIR}" # Raw JSON files from Pistachio database
  log_dir: &log_dir "${LOG_DIR}" # Preprocessing logs and debug information

  # Intermediate data directories
  dump_dir: &dump_dir "${DUMP_DIR}" # Initial chunks from raw JSON, one reaction dictionary per line
  grouped_dir: &grouped_dir "${GROUPED_DIR}" # Regrouped larger chunks for efficient processing
  temp_dedup_dir: &temp_dedup_dir "${TEMP_DEDUP_DIR}" # Temporary storage for locally deduplicated chunks
  split_dir: &split_dir "${SPLIT_DIR}" # Train/val/test splits by document ID (full_train.pickle, full_val.pickle, full_test.pickle)

  # Key intermediate files
  final_dedup_path: &final_dedup_path "${FINAL_DEDUP_PATH}" # Globally deduplicated reactions
  final_dedup_filtered_path: &final_dedup_filtered_path "${FINAL_DEDUP_FILTERED_PATH}" # After initial filtering (length, atom count, etc.)
  final_dedup_filtered_path_with_uncat: &final_dedup_filtered_path_with_uncat "${FINAL_DEDUP_FILTERED_WITH_UNCAT_PATH}" # including uncat reactions

  # Processed data directories and files
  agent_encoder_list_path: &agent_encoder_list_path "${AGENT_ENCODER_LIST_PATH}" # Agent vocabulary list
  agent_other_dict_path: &agent_other_dict_path "${AGENT_OTHER_DICT_PATH}" # Rare agent mappings (e.g., other_Pd)
  conv_rules_path: &conv_rules_path "${CONV_RULES_PATH}" # Agent standardization rules

  # Stage-specific filtered data
  stage1_dir: &stage1_dir "${STAGE1_DIR}" # Agent data
  stage2_dir: &stage2_dir "${STAGE2_DIR}" # Temperature data
  stage3_dir: &stage3_dir "${STAGE3_DIR}" # Reactant amount data
  stage4_dir: &stage4_dir "${STAGE4_DIR}" # Agent amount data

logging:
  log_dir: *log_dir
  debug_logging: false # detailed logging, failed reactions saved
  debug_stages:
    chunking: true
    data_collection: true
    initial_filter: true
    document_split: true
    condition_filter: true

chunking:
  raw_input_dir: *raw_dir
  initial_chunks_dir: *dump_dir
  grouped_chunks_dir: *grouped_dir=
  output_path: *final_dedup_filtered_path
  length_filters:
    product:
      min: 1
      max: 1
    reactant:
      min: 1
      max: 5
    agent:
      min: 0
      max: 5
  atom_filters:
    max_reactant_atoms: 50
    max_product_atoms: 50

document_split:
  input_path: *final_dedup_filtered_path
  output_dir: *split_dir
  split_ratios:
    train: 0.75
    val: 0.05
    test: 0.20
  seed: 42
  save_split_info: true # Save document IDs used in each split

# Agent Filters
stage_1_filter:
  input_dir: *split_dir
  output_dir: *stage1_dir

# Temperature Filters
stage_2_filter:
  input_dir: *split_dir
  output_dir: *stage2_dir
  temperature_range: # in Celsius
    lower: -100
    upper: 200

# Reactant Amount Filters
stage_3_filter:
  input_dir: *split_dir
  output_dir: *stage3_dir
  ratio_range:
    lower: 0.001
    upper: 7.0

# Agent Amount Filters
stage_4_filter:
  input_dir: *split_dir
  output_dir: *stage4_dir
  ratio_range:
    lower: 0.001
    upper: 1000.0
